import test from 'node:test';
import assert from 'node:assert/strict';
import { SEASON, SEASON_TWO, SEASON_THREE } from '../src/season.mjs';
import { LEVELS, GARDEN_LEVELS, POST_LEVELS, getLevel } from '../src/levels.mjs';
import { makeState } from '../src/core.mjs';
import { saveLevel, resetLevel, seasonProgress, levelUnlocked } from '../src/progress.mjs';
import { chapterVisitKey, pendingChapterVisit, completedReturnChapter, markChapterVisited, seenChapters } from '../src/chapter-progress.mjs';
const storage=()=>{const entries=new Map();return{entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v)}};
function finish(store,id){const l=getLevel(id),s=makeState(null,l);s.surfaces.forEach(f=>f.finish());l.items.forEach(i=>s.placed.add(i.id));s.taskFields.forEach(f=>f.finish());for(const t of l.operation.tasks||[])s.taskValues[t.id]=t.target??1;s.operationValue=l.operation.target??s.operationValue;s.brewTime=l.operation.duration;s.completed=true;assert.equal(saveLevel(store,s),true);}
test('completed earlier seasons cannot grant a third-season tour, stamp or finale',()=>{const store=storage();for(const l of [...LEVELS,...GARDEN_LEVELS])finish(store,l.id);assert.equal(pendingChapterVisit(store,SEASON),null);assert.equal(pendingChapterVisit(store,SEASON_TWO),null);assert.equal(pendingChapterVisit(store,SEASON_THREE),null);assert.equal(seasonProgress(store,SEASON_THREE).completedIds.size,0);assert.equal(levelUnlocked(store,getLevel('post-opening')),false);});
test('a chapter is offered only after all three earned results and visit survives replay',()=>{const store=storage(),first=SEASON_THREE.chapters[0];finish(store,first.levelIds[0]);finish(store,first.levelIds[1]);assert.equal(markChapterVisited(store,SEASON_THREE,first.id),false);assert.equal(pendingChapterVisit(store,SEASON_THREE),null);finish(store,first.levelIds[2]);assert.equal(pendingChapterVisit(store,SEASON_THREE)?.id,first.id);assert.equal(completedReturnChapter(store,SEASON_THREE,'fake'),null);const progressKeys=[...store.entries].map(([k,v])=>[k,v]);assert.equal(markChapterVisited(store,SEASON_THREE,first.id),true);for(const[k,v]of progressKeys)assert.equal(store.getItem(k),v);assert.equal(pendingChapterVisit(store,SEASON_THREE),null);resetLevel(store,getLevel(first.levelIds[2]));assert.equal(pendingChapterVisit(store,SEASON_THREE),null);assert.ok(seenChapters(store,SEASON_THREE).has(first.id));});
test('chapter two can be visited independently and the final scene closes pending tours',()=>{const store=storage();for(const id of SEASON_THREE.chapters[1].levelIds)finish(store,id);assert.equal(pendingChapterVisit(store,SEASON_THREE)?.id,'working');assert.equal(markChapterVisited(store,SEASON_THREE,'working'),true);for(const id of SEASON_THREE.chapters[0].levelIds)finish(store,id);assert.equal(pendingChapterVisit(store,SEASON_THREE)?.id,'welcome');for(const l of POST_LEVELS)finish(store,l.id);assert.equal(pendingChapterVisit(store,SEASON_THREE),null);assert.equal(seasonProgress(store,SEASON_THREE).finished,true);});
test('malformed tour records do not break earned progress and storage failures remain retryable',()=>{const store=storage();for(const id of SEASON_THREE.chapters[0].levelIds)finish(store,id);for(const bad of ['{','null',JSON.stringify({version:99,seen:['welcome']}),' '.repeat(4001)]){store.setItem(chapterVisitKey(SEASON_THREE),bad);assert.equal(pendingChapterVisit(store,SEASON_THREE)?.id,'welcome');}const broken={getItem:store.getItem,setItem(){throw Error('quota');}};assert.equal(markChapterVisited(broken,SEASON_THREE,'welcome'),false);assert.equal(pendingChapterVisit(store,SEASON_THREE)?.id,'welcome');});
