const FRONT = [0, 0, 0];
const TOP = [-Math.PI / 2, 0, 0];

export const WINDOW = {
  id: 'window',
  number: '07',
  name: '窗边座位',
  title: '留个位置，<br/>晒晒太阳。',
  description: '擦亮窗，铺好软垫。<br/>把街边的光请进来。',
  tags: '清洁 · 修补 · 采光',
  color: '#bec9a6',
  icon: 'window',
  revision: 1,
  steps: ['擦亮窗边', '铺好座位', '缝扣与开帘'],
  tidyTitle: '软垫铺好，<br/>留一席闲坐。',
  tidyHint: '坐垫平放在长椅上，靠垫倚向窗边，系带放在右侧窗帘。',
  actionTitle: '把阳光，<br/>请进来。',
  actionHint: '先缝好靠垫上的纽扣，再按住窗帘，慢慢拉开。',
  actionLabel: '迎接阳光',
  runningTitle: '树影落下，<br/>风也轻了。',
  runningHint: '这张窗边座位，终于等来了午后的光。',
  finishedTitle: '有个地方，<br/>可以发会儿呆。',
  finishedDescription: '纽扣缝牢，窗帘束好。<br/>树影在软垫上轻轻晃动。',
  caption: ['AFTERNOON LIGHT', 'A SEAT BY THE WINDOW'],
  room: { wall: '#d5d4bd', tile: '#ece8d9', accent: '#87976f' },
  operation: {
    kind: 'tasks',
    duration: 3.6,
    tasks: [
      {
        id: 'sew-button',
        name: '缝好纽扣',
        hint: '点一下靠垫中央的纽扣，把松开的线收好。',
        mode: 'tap',
        initial: 0,
        target: 1,
      },
      {
        id: 'open-curtain',
        name: '拉开窗帘',
        hint: '按住右侧窗帘，缓缓把光放进来。',
        mode: 'hold',
        initial: 0,
        target: 1,
        rate: 0.27,
        requires: ['sew-button'],
      },
    ],
  },
  surfaces: [
    {
      id: 'window-glass',
      name: '窗玻璃',
      width: 2.24,
      height: 1.13,
      weight: 0.45,
      seed: 717,
      completionThreshold: 0.87,
      material: 'glass',
      color: '#b8cbd0',
      position: [-0.35, 1.56, -0.874],
      rotation: FRONT,
      camera: { distance: 10.5, height: 3.8, lookX: -0.35, lookY: 1.55, lookZ: -0.8 },
    },
    {
      id: 'window-seat',
      name: '长椅座面',
      width: 2.44,
      height: 1.04,
      weight: 0.35,
      seed: 178,
      completionThreshold: 0.85,
      material: 'wood',
      color: '#d4b991',
      position: [-0.35, 0.437, 0.1],
      rotation: TOP,
      camera: { distance: 11.5, height: 7.7, lookX: -0.35, lookY: 0.45, lookZ: 0.1 },
    },
    {
      id: 'window-table',
      name: '边桌桌面',
      width: 0.76,
      height: 0.76,
      weight: 0.2,
      seed: 482,
      completionThreshold: 0.84,
      material: 'wood',
      color: '#d9bd94',
      position: [1.73, 0.533, 0.08],
      rotation: TOP,
      camera: { distance: 6.8, height: 5, lookX: 1.65, lookY: 0.52, lookZ: 0.1 },
    },
  ],
  items: [
    {
      id: 'seat-pad',
      kind: 'seat-pad',
      name: '长椅坐垫',
      hint: '平铺在窗下的长椅上。',
      mass: 0.3,
      size: [1.86, 0.15, 0.78],
      start: [-1.18, 0.15, 1.08],
      startRotation: [0, -0.12, 0],
      slot: [-0.38, 0.521, 0.09],
      slotRotation: FRONT,
      collider: 'box',
      dragHeight: 1.05,
      snapDistance: 0.4,
      placementLift: 0.24,
      marker: { position: [-0.38, 0.453, 0.09], radius: 0.34 },
    },
    {
      id: 'window-cushion',
      kind: 'window-cushion',
      name: '格纹靠垫',
      hint: '放在坐垫左侧，朝向窗边。',
      mass: 0.2,
      size: [0.65, 0.62, 0.21],
      start: [1.47, 0.2, 1.1],
      startRotation: [-Math.PI / 2, 0.2, 0.1],
      slot: [-0.94, 0.849, -0.22],
      slotRotation: [-0.17, 0.09, -0.05],
      collider: 'box',
      dragHeight: 1.24,
      placementLift: 0.21,
      requires: ['seat-pad'],
      marker: { position: [-0.94, 0.86, -0.06], plane: 'front', radius: 0.28 },
    },
    {
      id: 'curtain-tie',
      kind: 'curtain-tie',
      name: '窗帘系带',
      hint: '放在右侧窗帘下半部。',
      mass: 0.08,
      size: [0.31, 0.35, 0.13],
      start: [0.49, 0.2, 1.21],
      slot: [0.98, 1.3, -0.65],
      slotRotation: FRONT,
      collider: 'box',
      dragHeight: 1.64,
      marker: { position: [0.98, 1.3, -0.5], plane: 'front', radius: 0.2 },
    },
  ],
  obstacles: [
    { half: [1.31, 0.08, 0.58], position: [-0.35, 0.35, 0.08] },
    { half: [1.32, 1.09, 0.055], position: [-0.35, 1.14, -0.965] },
    { half: [0.42, 0.05, 0.42], position: [1.73, 0.478, 0.08] },
  ],
  cameras: {
    desktop: {
      default: { distance: 8.7, height: 3.8, lookX: -0.25, lookY: 1.0, lookZ: 0 },
      tidy: { distance: 9.1, height: 4.6, lookX: -0.25, lookY: 0.85, lookZ: 0.15 },
      finale: { distance: 7.8, height: 3.4, lookX: -0.25, lookY: 1.1, lookZ: 0 },
    },
    mobile: {
      default: { distance: 14.4, height: 4.8, lookX: -0.05, lookY: 1.0, lookZ: 0.05 },
      tidy: { distance: 17.6, height: 7.5, lookX: 0, lookY: 0.98, lookZ: 0.25 },
      finale: { distance: 12.6, height: 4.6, lookX: -0.24, lookY: 1.03, lookZ: 0.02 },
    },
  },
};

export const SIGN = {
  id: 'sign',
  number: '08',
  name: '门口招牌',
  title: '街角小店，<br/>有了名字。',
  description: '拭去旧锈，拼好店名。<br/>再给木牌添一层新颜色。',
  tags: '除锈 · 拼字 · 刷漆',
  color: '#91afa0',
  icon: 'sign',
  revision: 1,
  steps: ['除去旧锈', '拼好店名', '刷漆与抛光'],
  tidyTitle: '把名字，<br/>拼回街角。',
  tidyHint: '从左向右放好「街」「角」「小店」三块字牌。',
  actionTitle: '给旧木牌，<br/>添一层新绿。',
  actionHint: '在牌面上来回刷漆，覆盖浅色底漆，再按住边框抛光。',
  actionLabel: '挂起招牌',
  runningTitle: '灯亮了，<br/>名字也亮了。',
  runningHint: '路过的人，一眼就能认出这家小店。',
  finishedTitle: '街角小店。<br/>准备迎客。',
  finishedDescription: '新的绿，熟悉的名字。<br/>这块招牌又有了光彩。',
  caption: ['A NAME AT THE CORNER', 'THE LITTLE SHOP'],
  room: { wall: '#d1d3c4', tile: '#e9e5d9', accent: '#708d7e' },
  operation: {
    kind: 'tasks',
    duration: 4,
    tasks: [
      {
        id: 'paint-sign',
        name: '刷上新绿',
        hint: '在木牌浅色部分拖动刷子，慢慢涂满。',
        mode: 'brush',
        initial: 0,
        target: 1,
        field: {
          id: 'paint-sign',
          name: '招牌刷漆',
          width: 2.53,
          height: 1.14,
          weight: 1,
          seed: 882,
          completionThreshold: 0.88,
          material: 'wood',
          color: '#456f5b',
          beforeColor: '#c1b795',
          mask: {
            rects: [
              [0.032, 0.289, 0.289, 0.763],
              [0.324, 0.289, 0.581, 0.763],
              [0.644, 0.289, 0.988, 0.763],
            ],
          },
          position: [0, 1.22, -0.287],
          rotation: FRONT,
          camera: { distance: 11.4, height: 3.7, lookY: 1.25, lookZ: -0.15, lookX: 0 },
        },
      },
      {
        id: 'polish-frame',
        name: '抛光边框',
        hint: '按住右侧黄铜边框，擦出柔和的光泽。',
        mode: 'hold',
        targetPosition: [1.315, 1.23, -0.275],
        initial: 0,
        target: 1,
        rate: 0.3,
        requires: ['paint-sign'],
      },
    ],
  },
  surfaces: [
    {
      id: 'sign-board',
      name: '旧木牌面',
      width: 2.53,
      height: 1.14,
      weight: 0.48,
      seed: 254,
      completionThreshold: 0.87,
      material: 'wood',
      color: '#c1b795',
      position: [0, 1.22, -0.292],
      rotation: FRONT,
      camera: { distance: 11.5, height: 3.7, lookY: 1.22, lookZ: -0.2, lookX: 0 },
    },
    {
      id: 'sign-post',
      name: '金属立架',
      width: 0.23,
      height: 0.77,
      weight: 0.25,
      seed: 381,
      completionThreshold: 0.84,
      material: 'metal',
      color: '#53655c',
      position: [-1.39, 0.51, -0.246],
      rotation: FRONT,
      camera: { distance: 6.7, height: 2.7, lookX: -1.35, lookY: 0.51, lookZ: -0.2 },
    },
    {
      id: 'sign-foot',
      name: '招牌底座',
      width: 3.11,
      height: 0.65,
      weight: 0.27,
      seed: 511,
      completionThreshold: 0.85,
      material: 'metal',
      color: '#53655c',
      position: [0, 0.133, -0.08],
      rotation: TOP,
      camera: { distance: 12.5, height: 7.5, lookX: 0, lookY: 0.15, lookZ: -0.1 },
    },
  ],
  items: [
    ...[
      {
        id: 'sign-street',
        name: '「街」字牌',
        glyph: '街',
        width: 0.65,
        slotX: -0.86,
        startX: 1.62,
      },
      {
        id: 'sign-corner',
        name: '「角」字牌',
        glyph: '角',
        width: 0.65,
        slotX: -0.12,
        startX: -1.68,
      },
      {
        id: 'sign-shop',
        name: '「小店」字牌',
        glyph: '小店',
        width: 0.87,
        slotX: 0.8,
        startX: 0.03,
      },
    ].map((part, index) => ({
      id: part.id,
      kind: 'sign-letter',
      name: part.name,
      glyph: part.glyph,
      hint: `从左数第 ${index + 1} 格，拼成「街角小店」。`,
      mass: 0.16,
      size: [part.width, 0.54, 0.06],
      start: [part.startX, 0.14, 1.08],
      startRotation: [-Math.PI / 2, 0.08 * (index - 1), 0],
      slot: [part.slotX, 1.25, -0.241],
      slotRotation: FRONT,
      collider: 'box',
      dragHeight: 1.65,
      snapDistance: 0.3,
      placementLift: 0.15,
      marker: { position: [part.slotX, 1.25, -0.175], plane: 'front', radius: 0.25 },
      order: index + 1,
    })),
  ],
  obstacles: [
    { half: [1.33, 0.65, 0.075], position: [0, 1.23, -0.385] },
    { half: [1.61, 0.065, 0.37], position: [0, 0.065, -0.08] },
    { half: [0.13, 0.53, 0.1], position: [-1.39, 0.65, -0.36] },
    { half: [0.13, 0.53, 0.1], position: [1.39, 0.65, -0.36] },
  ],
  cameras: {
    desktop: {
      default: { distance: 8.5, height: 3.7, lookX: -0.3, lookY: 1.0, lookZ: 0 },
      tidy: { distance: 9.1, height: 4.2, lookX: -0.3, lookY: 0.95, lookZ: 0.2 },
      finale: { distance: 7.9, height: 3.15, lookX: -0.2, lookY: 1.2, lookZ: 0 },
    },
    mobile: {
      default: { distance: 13.3, height: 4.8, lookX: 0, lookY: 0.98, lookZ: 0 },
      tidy: { distance: 17, height: 6.8, lookX: 0, lookY: 0.9, lookZ: 0.3 },
      finale: { distance: 11.9, height: 3.6, lookX: 0, lookY: 1.16, lookZ: -0.12 },
    },
  },
};
