import { POST_EARLY_LEVELS } from './post-early-levels.mjs';
import { POST_MIDDLE_LEVELS } from './post-middle-levels.mjs';
import { POST_FINALE_LEVELS } from './post-finale-levels.mjs';
import { GARDEN_EARLY_LEVELS } from './garden-early-levels.mjs';
import { GARDEN_MIDDLE_LEVELS } from './garden-middle-levels.mjs';
import { GARDEN_FINALE_LEVELS } from './garden-finale-levels.mjs';
import { seasonForLevel, seasonLevelIds } from './season.mjs';
import { PLANT, CLOCK } from './restoration-levels.mjs';
import { WINDOW, SIGN } from './finishing-levels.mjs';
import { OPENING } from './shop-level.mjs';
import { COFFEE } from './core.mjs';

export const DESK = {
  id: 'desk',
  number: '02',
  name: '书桌',
  title: '给思绪，<br/>腾个位置。',
  description: '拂去墨迹，排好书册。<br/>把灯重新点亮。',
  tags: '清洁 · 排序 · 修复',
  color: '#a8b6c8',
  icon: 'desk',
  revision: 1,
  steps: ['擦净书桌', '按编号排书', '点亮台灯'],
  tidyTitle: '把书脊，<br/>排成一行。',
  tidyHint: '三册按 01 → 02 → 03 从左到右排列，再装回灯泡。',
  actionTitle: '把灯点亮吧。',
  actionHint: '书册有序，灯泡也已装好。',
  actionLabel: '点亮台灯',
  runningTitle: '留一束光，<br/>给阅读。',
  runningHint: '这张桌子又能安静地工作了。',
  finishedTitle: '书归书位。<br/>灯也亮了。',
  finishedDescription: '书脊连成完整的风景，<br/>给下一页留好了光。',
  caption: ['A QUIET PAGE', 'READING DESK'],
  operation: { kind: 'click', initial: 0, duration: 3 },
  room: { wall: '#c1cddd', tile: '#e5e8e1', accent: '#7c96b3' },
  surfaces: [
    {
      id: 'desk-mat',
      name: '书写桌垫',
      width: 2.65,
      height: 1.22,
      weight: 0.45,
      seed: 523,
      completionThreshold: 0.88,
      material: 'leather',
      color: '#657d8b',
      position: [-0.25, 0.013, 0.53],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 11.4, height: 7, lookY: 0.05, lookZ: 0.55, lookX: -0.1 },
    },
    {
      id: 'desk-shelf',
      name: '书架背板',
      width: 1.4,
      height: 1.0,
      weight: 0.35,
      seed: 864,
      material: 'wood',
      color: '#ead8b8',
      position: [-0.67, 0.65, -0.85],
      rotation: [0, 0, 0],
      camera: { distance: 7.8, height: 2.5, lookY: 0.65, lookZ: -0.65, lookX: -0.65 },
    },
    {
      id: 'desk-lamp',
      name: '灯座',
      width: 0.73,
      height: 0.6,
      weight: 0.2,
      seed: 272,
      material: 'metal',
      color: '#9aaebb',
      position: [1.57, 0.14, 0.29],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 6.8, height: 5, lookY: 0.14, lookZ: 0.3, lookX: 1.4 },
    },
  ],
  items: [
    ...[0, 1, 2].map((index) => ({
      id: `book-${index + 1}`,
      kind: 'book',
      name: `${String(index + 1).padStart(2, '0')} 号书册`,
      hint: `按编号排列，放进从左数第 ${index + 1} 格。`,
      mass: 0.42,
      size: [0.28, 0.86, 0.56],
      start: [-1.72 + index * 0.87, 0.22, 1.05 - index * 0.14],
      startRotation: [0, 0, Math.PI / 2],
      slot: [-1.05 + index * 0.36, 0.54, -0.4],
      slotRotation: [0, 0, 0],
      yaw: 0,
      collider: 'box',
      dragHeight: 1.1,
      snapDistance: 0.23,
      placementLift: 0.25,
      marker: { position: [-1.05 + index * 0.36, 0.54, -0.105], plane: 'front', radius: 0.13 },
      order: index + 1,
    })),
    {
      id: 'bulb',
      kind: 'bulb',
      name: '暖光灯泡',
      hint: '装入台灯的灯罩下方。',
      mass: 0.12,
      size: [0.23, 0.32, 0.23],
      start: [2, 0.23, 0.98],
      slot: [1.18, 1.34, 0.16],
      yaw: 0,
      collider: 'cylinder',
      dragHeight: 1.7,
      marker: { position: [1.18, 1.36, 0.33], plane: 'front', radius: 0.17 },
    },
  ],
  obstacles: [
    { half: [0.81, 0.06, 0.4], position: [-0.68, 0.05, -0.5] },
    { half: [0.75, 0.52, 0.045], position: [-0.68, 0.61, -0.9] },
    { half: [0.41, 0.07, 0.34], position: [1.57, 0.065, 0.28] },
  ],
  cameras: {
    mobile: {
      default: { distance: 12.5, height: 4.2, lookY: 0.78, lookZ: 0.2 },
      tidy: { distance: 16.8, height: 7.4, lookY: 0.6, lookZ: 0.2, lookX: -0.25 },
      finale: { distance: 12.7, height: 4.8, lookY: 0.82, lookZ: 0.15 },
    },
  },
};

export const TEA = {
  id: 'tea',
  number: '03',
  name: '茶席',
  title: '把一席茶，<br/>慢慢备好。',
  description: '洗净茶盘，摆好杯盏。<br/>注水时，慢一点就好。',
  tags: '清洁 · 对称归位 · 注水',
  color: '#c7a780',
  icon: 'tea',
  revision: 1,
  steps: ['清洁茶席', '摆好杯盏', '按住注水'],
  tidyTitle: '一碗居中，<br/>两杯相对。',
  tidyHint: '茶碗居中，杯子分放两侧，茶勺放在前方。',
  actionTitle: '把水，<br/>缓缓注入。',
  actionHint: '按住注水，松手就停。水位合适时会自动收尾。',
  actionLabel: '按住注水',
  runningTitle: '等茶叶，<br/>舒展开。',
  runningHint: '水温和茶香，慢慢安定下来。',
  finishedTitle: '一席整齐。<br/>一碗温茶。',
  finishedDescription: '杯盏成双，茶汤渐暖。<br/>此刻可以慢一点。',
  caption: ['A GENTLE POUR', 'TEA CEREMONY'],
  operation: {
    kind: 'pour',
    initial: 0,
    min: 0,
    max: 0.78,
    target: 0.78,
    rate: 0.26,
    duration: 3.5,
  },
  room: { wall: '#d7cbb6', tile: '#eeeadc', accent: '#a78055' },
  surfaces: [
    {
      id: 'tea-tray',
      name: '竹制茶盘',
      width: 2.8,
      height: 1.57,
      weight: 0.5,
      seed: 914,
      completionThreshold: 0.86,
      material: 'bamboo',
      color: '#b78a55',
      position: [0, 0.086, 0.19],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 12.0, height: 7, lookY: 0.08, lookZ: 0.2 },
    },
    {
      id: 'tea-tin',
      name: '陶瓷茶罐',
      width: 0.57,
      height: 0.73,
      weight: 0.27,
      seed: 346,
      material: 'ceramic',
      color: '#c8d6c4',
      position: [1.84, 0.43, -0.335],
      rotation: [0, 0, 0],
      camera: { distance: 6.5, height: 2, lookX: 1.8, lookY: 0.43, lookZ: -0.3 },
    },
    {
      id: 'tea-runner',
      name: '棉麻桌旗',
      width: 4.5,
      height: 0.39,
      weight: 0.23,
      seed: 348,
      completionThreshold: 0.82,
      material: 'linen',
      color: '#dcd6bf',
      position: [0, 0.005, 1.26],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 17, height: 9, lookY: 0.05, lookZ: 1.15 },
    },
  ],
  items: [
    {
      id: 'gaiwan',
      kind: 'gaiwan',
      name: '茶碗',
      hint: '放在茶盘中央。',
      mass: 0.3,
      size: [0.6, 0.28, 0.6],
      start: [-1.85, 0.25, 0.64],
      slot: [0, 0.25, 0.17],
      yaw: 0,
      collider: 'cylinder',
      marker: { position: [0, 0.095, 0.17], radius: 0.34 },
    },
    {
      id: 'teacup-left',
      kind: 'teacup',
      name: '左侧茶杯',
      hint: '与右杯相对，放在左侧。',
      mass: 0.13,
      size: [0.29, 0.19, 0.29],
      start: [1.65, 0.2, 0.8],
      slot: [-0.73, 0.2, 0.45],
      yaw: 0,
      collider: 'cylinder',
      marker: { position: [-0.73, 0.095, 0.45], radius: 0.2 },
    },
    {
      id: 'teacup-right',
      kind: 'teacup',
      name: '右侧茶杯',
      hint: '与左杯相对，放在右侧。',
      mass: 0.13,
      size: [0.29, 0.19, 0.29],
      start: [-1.65, 0.2, 1.02],
      slot: [0.73, 0.2, 0.45],
      yaw: 0,
      collider: 'cylinder',
      marker: { position: [0.73, 0.095, 0.45], radius: 0.2 },
    },
    {
      id: 'tea-scoop',
      kind: 'scoop',
      name: '竹茶勺',
      hint: '横放在茶盘前沿的细框里。',
      mass: 0.08,
      size: [0.72, 0.07, 0.15],
      start: [1.88, 0.16, 0.2],
      slot: [0, 0.126, 0.79],
      yaw: 0.42,
      collider: 'box',
      marker: { position: [0, 0.095, 0.79], radius: 0.18 },
    },
  ],
  obstacles: [
    { half: [1.47, 0.043, 0.84], position: [0, 0.032, 0.19] },
    { half: [0.32, 0.42, 0.28], position: [1.84, 0.41, -0.64] },
  ],
  cameras: {
    mobile: {
      default: { distance: 12, height: 6, lookY: 0.3, lookZ: 0.35 },
      tidy: { distance: 17, height: 8, lookY: 0.4, lookZ: 0.35 },
      finale: { distance: 6.6, height: 4, lookY: 0.36, lookZ: 0.25 },
    },
  },
};

export const RECORD = {
  id: 'record',
  number: '04',
  name: '唱片角',
  title: '让旧唱机，<br/>再唱一首。',
  description: '拂去尘土，接好传动。<br/>再把转速调稳。',
  tags: '清洁 · 顺序装配 · 调速',
  color: '#b99583',
  icon: 'record',
  revision: 1,
  steps: ['清洁唱机', '按顺序装配', '校准转速'],
  tidyTitle: '让传动，<br/>重新接起来。',
  tidyHint: '先装传动皮带，再放唱片，最后装回唱头。',
  actionTitle: '把转速，<br/>调进绿区。',
  actionHint: '拖动旋钮滑条，将转速调到 33⅓ RPM 附近，再放下唱针。',
  actionLabel: '放下唱针',
  runningTitle: '唱针落下，<br/>音乐回来。',
  runningHint: '一切重新运转起来。',
  finishedTitle: '唱机转了。<br/>房间也暖了。',
  finishedDescription: '皮带、唱片、唱头各就各位，<br/>一段旋律留在房间里。',
  caption: ['33⅓ RPM', 'THE LISTENING CORNER'],
  operation: {
    kind: 'dial',
    initial: 25,
    min: 25,
    max: 45,
    step: 0.1,
    target: 100 / 3,
    tolerance: 0.8,
    duration: 4,
    label: '转速',
    unit: 'RPM',
  },
  room: { wall: '#d6c4bc', tile: '#e8e0d5', accent: '#9b6d58' },
  surfaces: [
    {
      id: 'record-platter',
      name: '金属转盘',
      width: 1.48,
      height: 1.48,
      weight: 0.4,
      seed: 238,
      mask: { kind: 'disc', hole: 0.065 },
      material: 'platter',
      color: '#c2c6c2',
      position: [-0.43, 0.407, 0.06],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 8.4, height: 7.4, lookX: -0.43, lookY: 0.4, lookZ: 0.06 },
    },
    {
      id: 'record-controls',
      name: '唱臂面板',
      width: 0.69,
      height: 1.42,
      weight: 0.33,
      seed: 398,
      material: 'metal',
      color: '#d1b99b',
      position: [0.85, 0.379, 0.05],
      rotation: [-Math.PI / 2, 0, 0],
      camera: { distance: 8.2, height: 7, lookX: 0.85, lookY: 0.37, lookZ: 0.05 },
    },
    {
      id: 'record-front',
      name: '胡桃木机身',
      width: 2.6,
      height: 0.3,
      weight: 0.27,
      seed: 213,
      material: 'wood',
      color: '#b98b61',
      position: [0, 0.19, 0.907],
      rotation: [0, 0, 0],
      camera: { distance: 10.5, height: 2.4, lookY: 0.22, lookZ: 0.8 },
    },
  ],
  items: [
    {
      id: 'belt',
      kind: 'belt',
      name: '传动皮带',
      hint: '先把皮带套在金属转盘外围。',
      mass: 0.12,
      size: [1.34, 0.04, 1.34],
      start: [-1.85, 0.16, 0.78],
      slot: [-0.43, 0.414, 0.06],
      yaw: 0,
      collider: 'cylinder',
      dragHeight: 0.95,
      marker: { position: [-0.43, 0.418, 0.06], radius: 0.72 },
    },
    {
      id: 'record-disc',
      kind: 'vinyl',
      name: '黑胶唱片',
      hint: '装好皮带后，把唱片放上转盘。',
      mass: 0.2,
      size: [1.41, 0.035, 1.41],
      start: [1.8, 0.16, 0.79],
      slot: [-0.43, 0.447, 0.06],
      yaw: 0,
      collider: 'cylinder',
      dragHeight: 1.05,
      requires: ['belt'],
      marker: { position: [-0.43, 0.456, 0.06], radius: 0.48 },
    },
    {
      id: 'cartridge',
      kind: 'cartridge',
      name: '唱头',
      hint: '唱片放好后，将唱头接到唱臂末端。',
      mass: 0.09,
      size: [0.24, 0.13, 0.4],
      start: [-0.15, 0.16, 1.29],
      slot: [0.64, 0.6, 0.42],
      yaw: -0.3,
      collider: 'box',
      dragHeight: 0.95,
      requires: ['record-disc'],
      marker: { position: [0.64, 0.61, 0.42], radius: 0.18 },
    },
  ],
  obstacles: [{ half: [1.36, 0.19, 0.89], position: [0, 0.19, 0] }],
  cameras: {
    mobile: {
      default: { distance: 12.1, height: 7.7, lookY: 0.3, lookZ: 0.2 },
      tidy: { distance: 18.5, height: 9.5, lookY: 0.36, lookZ: 0.4 },
      finale: { distance: 11.2, height: 7.2, lookY: 0.42, lookZ: 0.1 },
    },
  },
};

export const LEVELS = Object.freeze([
  COFFEE,
  DESK,
  TEA,
  RECORD,
  PLANT,
  CLOCK,
  WINDOW,
  SIGN,
  OPENING,
]);
export const GARDEN_LEVELS = Object.freeze([...GARDEN_EARLY_LEVELS, ...GARDEN_MIDDLE_LEVELS, ...GARDEN_FINALE_LEVELS]);
export const POST_LEVELS = Object.freeze([...POST_EARLY_LEVELS, ...POST_MIDDLE_LEVELS, ...POST_FINALE_LEVELS]);
export const ALL_LEVELS = Object.freeze([...LEVELS, ...GARDEN_LEVELS, ...POST_LEVELS]);
export function getLevel(id) {
  return ALL_LEVELS.find((level) => level.id === id) || COFFEE;
}
export function nextLevel(id) {
  const ids = seasonLevelIds(seasonForLevel(id));
  return getLevel(ids[(ids.indexOf(id) + 1) % ids.length]);
}
