const horizontal = [-Math.PI / 2, 0, 0];

export const PLANT = {
  id: 'plant',
  number: '05',
  name: '绿植台',
  title: '给一片绿，<br/>一点照料。',
  description: '洗净花盆，收好工具。<br/>剪去枯叶，让新叶舒展开。',
  tags: '清洁 · 修剪 · 浇水',
  color: '#91ae88',
  icon: 'plant',
  revision: 1,
  steps: ['擦净绿植台', '工具各归其位', '修剪与浇水'],
  tidyTitle: '小小工具，<br/>整齐等候。',
  tidyHint: '喷壶放在托盘后方，小铲和修枝剪并排收在前方。',
  actionTitle: '照料一株，<br/>慢慢生长。',
  actionHint: '点掉三片枯叶，再按住浇水。松手就停，土壤湿润后便足够了。',
  actionLabel: '把绿意留在窗边',
  runningTitle: '水渗进土里，<br/>叶片舒展开。',
  runningHint: '照料过的小小生命，又有了精神。',
  finishedTitle: '枯叶落下。<br/>新绿留下。',
  finishedDescription: '花盆干净，工具整齐，<br/>窗边多了一片舒展的绿意。',
  caption: ['ROOM TO GROW', 'THE PLANT CORNER'],
  operation: {
    kind: 'tasks',
    initial: 0,
    duration: 3.5,
    tasks: [
      {
        id: 'prune-left',
        name: '剪去左侧枯叶',
        hint: '点一下左侧垂下的褐色叶片。',
        mode: 'tap',
        initial: 0,
        target: 1,
      },
      {
        id: 'prune-right',
        name: '剪去右侧枯叶',
        hint: '点一下右侧褐色叶片。',
        mode: 'tap',
        initial: 0,
        target: 1,
      },
      {
        id: 'prune-low',
        name: '剪去下方枯叶',
        hint: '点一下花盆上方的小片枯叶。',
        mode: 'tap',
        initial: 0,
        target: 1,
      },
      {
        id: 'water',
        name: '缓缓浇水',
        buttonLabel: '浇水',
        hint: '按住浇水，等土壤均匀湿润。',
        mode: 'hold',
        initial: 0,
        min: 0,
        max: 1,
        target: 1,
        rate: 0.23,
        requires: ['prune-left', 'prune-right', 'prune-low'],
      },
    ],
  },
  room: { wall: '#d5d5bc', tile: '#ebe9d9', accent: '#86a377' },
  surfaces: [
    {
      id: 'plant-pot',
      name: '青釉花盆',
      width: 1.15,
      height: 0.57,
      weight: 0.4,
      seed: 570,
      completionThreshold: 0.88,
      material: 'ceramic',
      color: '#a1b5a3',
      position: [-0.45, 0.34, 0.044],
      rotation: [0, 0, 0],
      camera: { distance: 8.1, height: 2.35, lookX: -0.45, lookY: 0.38, lookZ: 0.1 },
    },
    {
      id: 'plant-mat',
      name: '棉麻桌垫',
      width: 3.95,
      height: 0.52,
      weight: 0.35,
      seed: 571,
      completionThreshold: 0.84,
      material: 'linen',
      color: '#d1cfb5',
      position: [0, 0.009, 1.12],
      rotation: horizontal,
      camera: { distance: 15.7, height: 8.2, lookY: 0.1, lookZ: 1.02 },
    },
    {
      id: 'plant-tray',
      name: '工具托盘',
      width: 1.12,
      height: 1.25,
      weight: 0.25,
      seed: 572,
      completionThreshold: 0.86,
      material: 'metal',
      color: '#b8c2b0',
      position: [1.53, 0.049, -0.12],
      rotation: horizontal,
      camera: { distance: 8.3, height: 6, lookX: 1.48, lookY: 0.1, lookZ: -0.05 },
    },
  ],
  items: [
    {
      id: 'watering-can',
      kind: 'watering-can',
      name: '小喷壶',
      hint: '壶身放在托盘后方的大圆圈里。',
      mass: 0.3,
      size: [0.81, 0.48, 0.44],
      start: [-1.93, 0.31, 0.74],
      slot: [1.57, 0.29, -0.36],
      yaw: 0.3,
      slotRotation: [0, 0, 0],
      collider: 'box',
      dragHeight: 0.98,
      marker: { position: [1.57, 0.065, -0.36], radius: 0.29 },
    },
    {
      id: 'garden-trowel',
      kind: 'garden-trowel',
      name: '园艺小铲',
      hint: '沿托盘前方的右侧细格摆放。',
      mass: 0.14,
      size: [0.21, 0.07, 0.66],
      start: [0.39, 0.15, 1.14],
      slot: [1.77, 0.096, 0.22],
      yaw: -0.58,
      slotRotation: [0, 0, 0],
      collider: 'box',
      dragHeight: 0.73,
      marker: { position: [1.77, 0.064, 0.25], radius: 0.14 },
    },
    {
      id: 'pruning-shears',
      kind: 'pruning-shears',
      name: '修枝剪',
      hint: '放入托盘前方左侧的细格。',
      mass: 0.16,
      size: [0.24, 0.065, 0.58],
      start: [1.62, 0.14, 1.08],
      slot: [1.27, 0.095, 0.22],
      yaw: 0.57,
      slotRotation: [0, 0, 0],
      collider: 'box',
      dragHeight: 0.73,
      marker: { position: [1.27, 0.064, 0.25], radius: 0.14 },
    },
  ],
  obstacles: [
    { half: [0.62, 0.345, 0.45], position: [-0.45, 0.345, -0.42] },
    { half: [0.62, 0.023, 0.69], position: [1.53, 0.023, -0.12] },
  ],
  cameras: {
    desktop: {
      default: { distance: 8.4, height: 3.8, lookY: 0.75, lookZ: 0.1 },
      tidy: { distance: 8.9, height: 4.6, lookY: 0.6, lookZ: 0.15 },
      finale: { distance: 7.4, height: 3.1, lookX: -0.3, lookY: 0.95, lookZ: 0.04 },
    },
    mobile: {
      default: { distance: 12.7, height: 4.5, lookY: 0.85, lookZ: 0.18 },
      tidy: { distance: 18.6, height: 7.4, lookY: 0.54, lookZ: 0.25, lookX: -0.23 },
      finale: { distance: 8.6, height: 3.9, lookX: -0.45, lookY: 1.03, lookZ: 0.05 },
    },
  },
};

const gears = [
  {
    id: 'clock-large-gear',
    name: '大齿轮',
    radius: 0.275,
    teeth: 18,
    start: [-1.91, 0.11, 0.66],
    slot: [-0.49, 1.04, 0.07],
    order: 1,
    hint: '先装左上方的大齿轮，让传动从这里开始。',
  },
  {
    id: 'clock-medium-gear',
    name: '中齿轮',
    radius: 0.205,
    teeth: 14,
    start: [1.58, 0.11, 0.67],
    slot: [-0.02, 1.04, 0.075],
    order: 2,
    requires: ['clock-large-gear'],
    hint: '接在大齿轮右侧，让两组齿咬合。',
  },
  {
    id: 'clock-small-gear',
    name: '小齿轮',
    radius: 0.145,
    teeth: 10,
    start: [1.72, 0.11, 1.14],
    slot: [0.19, 0.77, 0.08],
    order: 3,
    requires: ['clock-medium-gear'],
    hint: '装到中齿轮右下方的小轴上。',
  },
];

export const CLOCK = {
  id: 'clock',
  number: '06',
  name: '旧挂钟',
  title: '让旧挂钟，<br/>重新走动。',
  description: '擦亮钟面，接好齿轮。<br/>把时针拨到约好的时间。',
  tags: '清洁 · 齿轮装配 · 对时',
  color: '#bca073',
  icon: 'clock',
  revision: 1,
  steps: ['擦亮旧挂钟', '接好齿轮与钟摆', '校准到 10:10'],
  tidyTitle: '一颗齿轮，<br/>接着一颗。',
  tidyHint: '从大到小装回三颗齿轮，最后把钟摆挂到中央的轴上。',
  actionTitle: '把这一刻，<br/>对准 10:10。',
  actionHint: '拖动时间滑条，观察长短指针；调到 10:10 附近后，拨动钟摆。',
  actionLabel: '轻轻拨动钟摆',
  runningTitle: '滴答，滴答。<br/>时间又向前。',
  runningHint: '齿轮相接，钟摆摇动，熟悉的节奏回来了。',
  finishedTitle: '齿轮咬合。<br/>时间重新流动。',
  finishedDescription: '三颗齿轮各司其职，<br/>小店里又响起轻柔的滴答声。',
  caption: ['TEN PAST TEN', 'THE OLD WALL CLOCK'],
  operation: {
    kind: 'tasks',
    initial: 0,
    duration: 4,
    tasks: [
      {
        id: 'set-time',
        name: '校准到 10:10',
        hint: '长针指向 2，短针略过 10。',
        mode: 'dial',
        initial: 540,
        min: 540,
        max: 660,
        step: 1,
        target: 610,
        tolerance: 3,
        unit: '',
        format: 'time',
        label: '钟面时间',
      },
    ],
  },
  room: { wall: '#d8cbb8', tile: '#e9e3d6', accent: '#a88c66' },
  surfaces: [
    {
      id: 'clock-glass',
      name: '玻璃钟面',
      width: 1.31,
      height: 1.31,
      weight: 0.47,
      seed: 681,
      completionThreshold: 0.89,
      mask: { kind: 'disc' },
      material: 'ceramic',
      color: '#eee7d4',
      position: [-0.2, 1.88, -0.047],
      rotation: [0, 0, 0],
      camera: { distance: 8.8, height: 3.25, lookX: -0.2, lookY: 1.88, lookZ: 0 },
    },
    {
      id: 'clock-case',
      name: '胡桃木钟壳',
      width: 0.22,
      height: 1.84,
      weight: 0.26,
      seed: 682,
      completionThreshold: 0.85,
      material: 'wood',
      color: '#b28860',
      position: [-1.06, 1.32, 0.018],
      rotation: [0, 0, 0],
      camera: { distance: 7.2, height: 2.8, lookX: -1.05, lookY: 1.36, lookZ: 0.02 },
    },
    {
      id: 'clock-base',
      name: '橡木底座',
      width: 2.2,
      height: 0.13,
      weight: 0.27,
      seed: 683,
      completionThreshold: 0.85,
      material: 'wood',
      color: '#d1ad7c',
      position: [-0.2, 0.08, 0.276],
      rotation: [0, 0, 0],
      camera: { distance: 9.2, height: 2.2, lookX: -0.2, lookY: 0.12, lookZ: 0.25 },
    },
  ],
  items: [
    ...gears.map((gear) => ({
      ...gear,
      kind: 'clock-gear',
      mass: 0.15 + gear.radius * 0.4,
      size: [gear.radius * 2, gear.radius * 2, 0.075],
      startRotation: horizontal,
      slotRotation: [0, 0, 0],
      collider: 'box',
      dragHeight: 1.45,
      snapDistance: 0.24,
      placementLift: 0.18,
      marker: {
        position: [gear.slot[0], gear.slot[1], 0.13],
        plane: 'front',
        radius: gear.radius * 0.83,
      },
    })),
    {
      id: 'clock-pendulum',
      kind: 'clock-pendulum',
      name: '黄铜钟摆',
      hint: '齿轮装好后，将钟摆上端挂在中央的小轴上。',
      mass: 0.32,
      size: [0.36, 0.72, 0.09],
      start: [-1.67, 0.12, 1.15],
      startRotation: horizontal,
      slot: [-0.2, 0.54, 0.175],
      slotRotation: [0, 0, 0],
      collider: 'box',
      dragHeight: 1.1,
      requires: ['clock-small-gear'],
      marker: { position: [-0.2, 0.54, 0.24], plane: 'front', radius: 0.17 },
    },
  ],
  obstacles: [
    { half: [0.98, 1.18, 0.24], position: [-0.2, 1.34, -0.235] },
    { half: [1.16, 0.08, 0.42], position: [-0.2, 0.08, -0.15] },
  ],
  cameras: {
    desktop: {
      default: { distance: 8.2, height: 3.1, lookY: 1.15, lookZ: 0.05 },
      tidy: { distance: 9.3, height: 3.8, lookY: 1, lookZ: 0.14 },
      finale: { distance: 7.5, height: 2.9, lookX: -0.2, lookY: 1.25, lookZ: 0.03 },
    },
    mobile: {
      default: { distance: 12.1, height: 4.1, lookY: 1.25, lookZ: 0.07 },
      tidy: { distance: 17.6, height: 6.2, lookY: 0.88, lookZ: 0.3 },
      finale: { distance: 11.2, height: 3.8, lookX: -0.2, lookY: 1.36, lookZ: 0.05 },
    },
  },
};
