const overviewCamera = { distance: 24, height: 13, lookY: 0.9, lookZ: 0.08, lookX: 0.12 };

export const OPENING = {
  id: 'opening',
  number: '09',
  name: '小店开张',
  title: '熟悉的日常，<br/>重新开门。',
  description: '八处亲手修好的角落，终于回到同一家店。<br/>点亮灯，放一首歌，备好第一杯咖啡。',
  tags: '全季成果 · 开店仪式',
  color: '#b98b58',
  icon: 'opening',
  revision: 1,
  steps: ['八处焕新', '最后的准备', '开门营业'],
  tidyTitle: '每一处，<br/>都准备好了。',
  tidyHint: '八个工作台的修复成果都在这里。',
  actionTitle: '为这间店，<br/>添一点温度。',
  actionHint: '点亮阅读灯、放下唱针，再准备第一杯咖啡。可以点店里的物件，也可以使用下方按钮。',
  actionLabel: '开门营业',
  runningTitle: '开门，<br/>迎接好日子。',
  runningHint: '光照进来，唱片轻转。这间小店又有了日常。',
  finishedTitle: '这一季，<br/>收拾好了。',
  finishedDescription: '从第一块污渍，到这一屋子的温暖。<br/>谢谢你，让街角旧店重新亮起来。',
  caption: ['A LITTLE RESET', 'THE CORNER SHOP · SEASON 01'],
  operation: {
    kind: 'tasks',
    duration: 6,
    tasks: [
      {
        id: 'opening-lamp',
        name: '点亮阅读灯',
        hint: '让一束暖光落在排好的书旁。',
        mode: 'tap',
        target: 1,
        initial: 0,
      },
      {
        id: 'opening-music',
        name: '放一首唱片',
        hint: '让修好的唱片机，陪伴小店的第一天。',
        mode: 'tap',
        target: 1,
        initial: 0,
      },
      {
        id: 'opening-coffee',
        name: '准备第一杯咖啡',
        hint: '咖啡香气和热气，就是开店的信号。',
        mode: 'tap',
        target: 1,
        initial: 0,
      },
    ],
  },
  room: { custom: true, wall: '#ddd8c9', tile: '#ece2ce', accent: '#719681' },
  surfaces: [],
  items: [],
  obstacles: [],
  cameras: {
    desktop: { distance: 10.8, height: 7.8, lookY: 0.8, lookZ: 0.03, lookX: -0.3 },
    mobile: {
      default: overviewCamera,
      tidy: overviewCamera,
      finale: overviewCamera,
      overview: overviewCamera,
    },
  },
};
